version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: 'mongo'
    volumes:
      - "goal-db:/data/db"
    env_file:
      - cred.env
  backend:
    depends_on:
      - mongodb
    container_name: goal-backend
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - goal-log:/app/logs
      - /app/node_modules
      - ./backend/:/app
  frontend:
    container_name: goal-frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend/src/:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  goal-db:
  goal-log: